theme: jekyll-theme-dinky
title: AWS FAQs
description: AWS has more than 200 services, covering IAAS, PAAS, and SAAS. We study the core AWS services so that developers can start their development, at teh same time they gain the concepts to expand their expertise to other services. 
